tags: ''
statDistribution: ''
stats:
  act_count:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_duration:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_heat:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  mass:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  scrap_value:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_concussion:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage_radius:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact_radius:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_proj_lifetime:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_proj_ricochet:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_max:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_min:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle_moving:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_speed:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
